// This file is @generated by prost-build.
/// ============ 通用物品 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Item {
    /// 物品ID
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 数量
    #[prost(int64, tag = "2")]
    pub count: i64,
    /// 过期时间
    #[prost(int64, tag = "3")]
    pub expire_time: i64,
    /// field 4 reserved
    /// google.protobuf.Any detail = 5;  // 详情 (略)
    ///
    /// UID
    #[prost(int64, tag = "6")]
    pub uid: i64,
    /// 是否新获得
    #[prost(bool, tag = "7")]
    pub is_new: bool,
    /// 变异类型
    #[prost(int64, repeated, tag = "8")]
    pub mutant_types: ::prost::alloc::vec::Vec<i64>,
}
/// 背包（物品列表）
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemBag {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<Item>,
}
/// ============ 物品变化 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemChg {
    /// 物品信息
    #[prost(message, optional, tag = "1")]
    pub item: ::core::option::Option<Item>,
    /// 变化量 (正数增加, 负数减少)
    #[prost(int64, tag = "2")]
    pub delta: i64,
}
