// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetIllustratedListV2Request {
    #[prost(bool, tag = "1")]
    pub refresh: bool,
    #[prost(bool, tag = "2")]
    pub full: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IllustratedItem {
    #[prost(int64, tag = "1")]
    pub seed_id: i64,
    #[prost(bool, tag = "2")]
    pub unlocked: bool,
    #[prost(bool, tag = "3")]
    pub planted: bool,
    #[prost(int32, tag = "4")]
    pub planted_count: i32,
    #[prost(int32, tag = "5")]
    pub harvest_count: i32,
    #[prost(int32, tag = "6")]
    pub category: i32,
    #[prost(bytes = "vec", tag = "7")]
    pub reward_info: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "8")]
    pub has_reward: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetIllustratedListV2Reply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<IllustratedItem>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimAllRewardsV2Request {
    #[prost(bool, tag = "1")]
    pub only_claimable: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimAllRewardsV2Reply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    #[prost(message, repeated, tag = "4")]
    pub bonus_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IllustratedRewardRedDotNotifyV2 {}
