// This file is @generated by prost-build.
/// 获取背包
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BagRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BagReply {
    /// 与 game 一致，背包数据在 item_bag 里
    #[prost(message, optional, tag = "1")]
    pub item_bag: ::core::option::Option<super::super::corepb::ItemBag>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SellRequest {
    /// 要出售的物品列表 (id + count)
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SellReply {
    /// 出售的物品
    #[prost(message, repeated, tag = "1")]
    pub sell_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    /// 获得的物品（常见: 1001=金币, 1002=点券）
    #[prost(message, repeated, tag = "2")]
    pub get_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UseRequest {
    #[prost(int64, tag = "1")]
    pub item_id: i64,
    #[prost(int64, tag = "2")]
    pub count: i64,
    #[prost(int64, repeated, tag = "3")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UseReply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUseRequest {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUseReply {
    #[prost(message, repeated, tag = "1")]
    pub used_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
/// ============ 物品变化通知 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemNotify {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::ItemChg>,
}
