// This file is @generated by prost-build.
/// ============ 好友农场摘要信息 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Plant {
    /// 缺水倒计时秒
    #[prost(int64, tag = "1")]
    pub dry_time_sec: i64,
    /// 长草倒计时秒
    #[prost(int64, tag = "2")]
    pub weed_time_sec: i64,
    /// 生虫倒计时秒
    #[prost(int64, tag = "3")]
    pub insect_time_sec: i64,
    /// 成熟倒计时秒
    #[prost(int64, tag = "4")]
    pub ripe_time_sec: i64,
    /// 成熟果实ID
    #[prost(int64, tag = "5")]
    pub ripe_fruit_id: i64,
    /// 可偷数量
    #[prost(int64, tag = "6")]
    pub steal_plant_num: i64,
    /// 缺水地块数
    #[prost(int64, tag = "7")]
    pub dry_num: i64,
    /// 有草地块数
    #[prost(int64, tag = "8")]
    pub weed_num: i64,
    /// 有虫地块数
    #[prost(int64, tag = "9")]
    pub insect_num: i64,
}
/// ============ 标签 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Tags {
    #[prost(bool, tag = "1")]
    pub is_new: bool,
    #[prost(bool, tag = "2")]
    pub is_follow: bool,
}
/// ============ 好友信息 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameFriend {
    #[prost(int64, tag = "1")]
    pub gid: i64,
    #[prost(string, tag = "2")]
    pub open_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub remark: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub level: i64,
    #[prost(int64, tag = "7")]
    pub gold: i64,
    #[prost(message, optional, tag = "8")]
    pub tags: ::core::option::Option<Tags>,
    #[prost(message, optional, tag = "9")]
    pub plant: ::core::option::Option<Plant>,
    /// field 11 reserved
    /// Illustrated illustrated = 12;  // 略
    /// repeated AvatarFrame equip_avatar_frames = 13;  // 略
    #[prost(int32, tag = "10")]
    pub authorized_status: i32,
}
/// --- 获取所有好友 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAllRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllReply {
    #[prost(message, repeated, tag = "1")]
    pub game_friends: ::prost::alloc::vec::Vec<GameFriend>,
    /// repeated Invitation invitations = 2;  // 略
    #[prost(int64, tag = "3")]
    pub application_count: i64,
}
/// --- 同步好友 (带 open_ids) ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncAllRequest {
    /// field 1 reserved
    #[prost(string, repeated, tag = "2")]
    pub open_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncAllReply {
    #[prost(message, repeated, tag = "1")]
    pub game_friends: ::prost::alloc::vec::Vec<GameFriend>,
    /// repeated Invitation invitations = 2;  // 略
    #[prost(int64, tag = "3")]
    pub application_count: i64,
}
/// 申请信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Application {
    #[prost(int64, tag = "1")]
    pub gid: i64,
    #[prost(int64, tag = "2")]
    pub time_at: i64,
    #[prost(string, tag = "3")]
    pub open_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub avatar_url: ::prost::alloc::string::String,
    /// repeated AvatarFrame equip_avatar_frames = 7;  // 略
    #[prost(int64, tag = "6")]
    pub level: i64,
}
/// --- 获取好友申请列表 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetApplicationsRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetApplicationsReply {
    #[prost(message, repeated, tag = "1")]
    pub applications: ::prost::alloc::vec::Vec<Application>,
    /// 是否屏蔽申请
    #[prost(bool, tag = "2")]
    pub block_applications: bool,
}
/// --- 同意好友申请 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptFriendsRequest {
    #[prost(int64, repeated, tag = "1")]
    pub friend_gids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptFriendsReply {
    #[prost(message, repeated, tag = "1")]
    pub friends: ::prost::alloc::vec::Vec<GameFriend>,
}
/// --- 拒绝好友申请 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RejectFriendsRequest {
    #[prost(int64, repeated, tag = "1")]
    pub friend_gids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RejectFriendsReply {}
/// --- 设置屏蔽申请 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetBlockApplicationsRequest {
    #[prost(bool, tag = "1")]
    pub block: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetBlockApplicationsReply {
    #[prost(bool, tag = "1")]
    pub block: bool,
}
/// 收到好友申请通知
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendApplicationReceivedNotify {
    #[prost(message, repeated, tag = "1")]
    pub applications: ::prost::alloc::vec::Vec<Application>,
}
/// 好友添加成功通知 (对方同意后)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FriendAddedNotify {
    #[prost(message, repeated, tag = "1")]
    pub friends: ::prost::alloc::vec::Vec<GameFriend>,
}
