// This file is @generated by prost-build.
/// 获取商场列表请求
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetMallListBySlotTypeRequest {
    /// 商场类型
    #[prost(int32, tag = "1")]
    pub slot_type: i32,
}
/// 获取商场列表响应
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMallListBySlotTypeResponse {
    /// 商品列表（每个是序列化的MallGoods）
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub goods_list: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// 时间戳
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
}
/// 商品信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MallGoods {
    /// 商品ID
    #[prost(int32, tag = "1")]
    pub goods_id: i32,
    /// 商品名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 商品类型
    #[prost(int32, tag = "3")]
    pub r#type: i32,
    /// 物品ID列表（序列化数据）
    #[prost(bytes = "vec", tag = "4")]
    pub item_ids: ::prost::alloc::vec::Vec<u8>,
    /// 价格（序列化数据）
    #[prost(bytes = "vec", tag = "5")]
    pub price: ::prost::alloc::vec::Vec<u8>,
    /// 是否免费
    #[prost(bool, tag = "6")]
    pub is_free: bool,
    /// 限购信息（序列化数据）
    #[prost(bytes = "vec", tag = "7")]
    pub limit: ::prost::alloc::vec::Vec<u8>,
    /// 是否限购
    #[prost(bool, tag = "8")]
    pub is_limited: bool,
    /// 折扣信息
    #[prost(string, tag = "10")]
    pub discount: ::prost::alloc::string::String,
}
/// 购买请求
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PurchaseRequest {
    /// 商品ID
    #[prost(int32, tag = "1")]
    pub goods_id: i32,
    /// 购买数量
    #[prost(int32, tag = "2")]
    pub count: i32,
}
/// 购买响应
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PurchaseResponse {
    /// 商品ID
    #[prost(int32, tag = "1")]
    pub goods_id: i32,
    /// 购买数量
    #[prost(int32, tag = "2")]
    pub count: i32,
    /// 奖励信息
    #[prost(bytes = "vec", tag = "3")]
    pub reward_info: ::prost::alloc::vec::Vec<u8>,
    /// 购买结果
    #[prost(bytes = "vec", tag = "5")]
    pub result: ::prost::alloc::vec::Vec<u8>,
}
/// 月卡信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetMonthCardInfosRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MonthCardInfo {
    #[prost(int32, tag = "1")]
    pub goods_id: i32,
    #[prost(message, optional, tag = "2")]
    pub reward: ::core::option::Option<super::super::corepb::Item>,
    #[prost(bool, tag = "3")]
    pub can_claim: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMonthCardInfosReply {
    #[prost(message, repeated, tag = "1")]
    pub infos: ::prost::alloc::vec::Vec<MonthCardInfo>,
}
/// 领取月卡奖励
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimMonthCardRewardRequest {
    #[prost(int32, tag = "1")]
    pub goods_id: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimMonthCardRewardReply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
