// This file is @generated by prost-build.
/// --- 检查是否可以分享 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckCanShareRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckCanShareReply {
    /// 是否可以分享
    #[prost(bool, tag = "1")]
    pub can_share: bool,
}
/// --- 报告分享 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReportShareRequest {
    /// 是否已分享
    #[prost(bool, tag = "1")]
    pub shared: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReportShareReply {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// --- 领取分享奖励 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimShareRewardRequest {
    /// 请求领取
    #[prost(bool, tag = "1")]
    pub claimed: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimShareRewardReply {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 是否有奖励
    #[prost(bool, tag = "2")]
    pub has_reward: bool,
    /// 奖励物品列表
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
