// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetEmailListRequest {
    #[prost(int32, tag = "1")]
    pub box_type: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmailItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub mail_type: i32,
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub claimed: bool,
    #[prost(bool, tag = "5")]
    pub has_reward: bool,
    #[prost(string, tag = "7")]
    pub subtitle: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEmailListReply {
    #[prost(message, repeated, tag = "1")]
    pub emails: ::prost::alloc::vec::Vec<EmailItem>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadEmailRequest {
    #[prost(int32, tag = "1")]
    pub box_type: i32,
    #[prost(string, tag = "2")]
    pub email_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReadEmailReply {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimEmailRequest {
    #[prost(int32, tag = "1")]
    pub box_type: i32,
    #[prost(string, tag = "2")]
    pub email_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimEmailReply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchClaimEmailRequest {
    #[prost(int32, tag = "1")]
    pub box_type: i32,
    #[prost(string, tag = "2")]
    pub email_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchClaimEmailReply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
