// This file is @generated by prost-build.
/// ============ 商店概览 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShopProfile {
    /// 商店ID
    #[prost(int64, tag = "1")]
    pub shop_id: i64,
    /// 商店名称
    #[prost(string, tag = "2")]
    pub shop_name: ::prost::alloc::string::String,
    /// 商店类型
    #[prost(int32, tag = "3")]
    pub shop_type: i32,
}
/// ============ 商品信息 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GoodsInfo {
    /// 商品ID (用于购买)
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 已购买数量
    #[prost(int64, tag = "2")]
    pub bought_num: i64,
    /// 价格 (金币)
    #[prost(int64, tag = "3")]
    pub price: i64,
    /// 限购数量 (0=不限购)
    #[prost(int64, tag = "4")]
    pub limit_count: i64,
    /// 是否已解锁
    #[prost(bool, tag = "5")]
    pub unlocked: bool,
    /// 物品ID (即种子ID)
    #[prost(int64, tag = "6")]
    pub item_id: i64,
    /// 每次购买获得数量
    #[prost(int64, tag = "7")]
    pub item_count: i64,
    /// 解锁条件
    #[prost(message, repeated, tag = "8")]
    pub conds: ::prost::alloc::vec::Vec<Cond>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Cond {
    /// CondType
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// 参数值 (如等级要求的等级数)
    #[prost(int64, tag = "2")]
    pub param: i64,
}
/// --- 获取商店列表 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShopProfilesRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShopProfilesReply {
    #[prost(message, repeated, tag = "1")]
    pub shop_profiles: ::prost::alloc::vec::Vec<ShopProfile>,
}
/// --- 获取商店商品 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShopInfoRequest {
    #[prost(int64, tag = "1")]
    pub shop_id: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShopInfoReply {
    #[prost(message, repeated, tag = "1")]
    pub goods_list: ::prost::alloc::vec::Vec<GoodsInfo>,
}
/// --- 购买商品 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BuyGoodsRequest {
    /// 商品ID (GoodsInfo.id)
    #[prost(int64, tag = "1")]
    pub goods_id: i64,
    /// 购买数量
    #[prost(int64, tag = "2")]
    pub num: i64,
    /// 单价
    #[prost(int64, tag = "3")]
    pub price: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuyGoodsReply {
    /// 更新后的商品信息
    #[prost(message, optional, tag = "1")]
    pub goods: ::core::option::Option<GoodsInfo>,
    /// 获得的物品
    #[prost(message, repeated, tag = "2")]
    pub get_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    /// 消耗的物品
    #[prost(message, repeated, tag = "3")]
    pub cost_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
/// --- 商品解锁推送 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GoodsUnlockNotify {
    #[prost(message, repeated, tag = "1")]
    pub goods_list: ::prost::alloc::vec::Vec<GoodsInfo>,
}
/// ============ 解锁条件 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CondType {
    Unknown = 0,
    /// 最低等级要求
    MinLevel = 1,
    /// 需要解锁卡
    UnlockCard = 2,
}
impl CondType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "COND_TYPE_UNKNOWN",
            Self::MinLevel => "MIN_LEVEL",
            Self::UnlockCard => "UNLOCK_CARD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COND_TYPE_UNKNOWN" => Some(Self::Unknown),
            "MIN_LEVEL" => Some(Self::MinLevel),
            "UNLOCK_CARD" => Some(Self::UnlockCard),
            _ => None,
        }
    }
}
