// This file is @generated by prost-build.
/// ============ 土地信息 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LandInfo {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(bool, tag = "2")]
    pub unlocked: bool,
    #[prost(int64, tag = "3")]
    pub level: i64,
    #[prost(int64, tag = "4")]
    pub max_level: i64,
    #[prost(bool, tag = "5")]
    pub could_unlock: bool,
    #[prost(bool, tag = "6")]
    pub could_upgrade: bool,
    #[prost(message, optional, tag = "7")]
    pub unlock_condition: ::core::option::Option<LandUnlockCondition>,
    #[prost(message, optional, tag = "8")]
    pub upgrade_condition: ::core::option::Option<LandUpgradeCondition>,
    #[prost(message, optional, tag = "9")]
    pub buff: ::core::option::Option<land_info::Buff>,
    #[prost(message, optional, tag = "10")]
    pub plant: ::core::option::Option<PlantInfo>,
    #[prost(bool, tag = "11")]
    pub is_shared: bool,
    #[prost(bool, tag = "12")]
    pub can_share: bool,
    #[prost(int64, tag = "13")]
    pub master_land_id: i64,
    #[prost(int64, repeated, tag = "14")]
    pub slave_land_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, tag = "15")]
    pub land_size: i64,
    #[prost(int64, tag = "16")]
    pub lands_level: i64,
}
/// Nested message and enum types in `LandInfo`.
pub mod land_info {
    /// 土地buff
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct Buff {
        #[prost(int64, tag = "1")]
        pub plant_yield_bonus: i64,
        #[prost(int64, tag = "2")]
        pub planting_time_reduction: i64,
        #[prost(int64, tag = "3")]
        pub plant_exp_bonus: i64,
    }
}
/// 土地解锁条件 (简化)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LandUnlockCondition {
    #[prost(int64, tag = "1")]
    pub need_level: i64,
    /// ... 其他条件字段
    #[prost(int64, tag = "2")]
    pub need_gold: i64,
}
/// 土地升级条件 (简化)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LandUpgradeCondition {
    #[prost(int64, tag = "1")]
    pub need_level: i64,
    /// ... 其他条件字段
    #[prost(int64, tag = "2")]
    pub need_gold: i64,
}
/// ============ 植物信息 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlantInfo {
    /// 植物/种子ID
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// field 3 reserved
    ///
    /// 生长阶段列表
    #[prost(message, repeated, tag = "4")]
    pub phases: ::prost::alloc::vec::Vec<PlantPhaseInfo>,
    /// 季节
    #[prost(int64, tag = "5")]
    pub season: i64,
    /// 缺水次数 (>0需要浇水)
    #[prost(int64, tag = "6")]
    pub dry_num: i64,
    /// fields 7,8 reserved
    ///
    /// 被偷次数
    #[prost(int64, tag = "9")]
    pub stole_num: i64,
    /// 果实ID
    #[prost(int64, tag = "10")]
    pub fruit_id: i64,
    /// 果实数量
    #[prost(int64, tag = "11")]
    pub fruit_num: i64,
    /// 放草的人 (非空=有草)
    #[prost(int64, repeated, tag = "12")]
    pub weed_owners: ::prost::alloc::vec::Vec<i64>,
    /// 放虫的人 (非空=有虫)
    #[prost(int64, repeated, tag = "13")]
    pub insect_owners: ::prost::alloc::vec::Vec<i64>,
    /// 偷菜的人
    #[prost(int64, repeated, tag = "14")]
    pub stealers: ::prost::alloc::vec::Vec<i64>,
    /// 生长秒数
    #[prost(int64, tag = "15")]
    pub grow_sec: i64,
    /// 是否可偷
    #[prost(bool, tag = "16")]
    pub stealable: bool,
    /// 剩余施肥次数
    #[prost(int64, tag = "17")]
    pub left_inorc_fert_times: i64,
    /// 剩余果实数
    #[prost(int64, tag = "18")]
    pub left_fruit_num: i64,
    /// 偷菜亲密度等级
    #[prost(int64, tag = "19")]
    pub steal_intimacy_level: i64,
    /// 变异配置ID
    #[prost(int64, repeated, tag = "20")]
    pub mutant_config_ids: ::prost::alloc::vec::Vec<i64>,
    /// 是否被催熟
    #[prost(bool, tag = "21")]
    pub is_nudged: bool,
}
/// ============ 生长阶段详情 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlantPhaseInfo {
    /// PlantPhase 枚举值
    #[prost(int32, tag = "1")]
    pub phase: i32,
    /// 阶段开始时间
    #[prost(int64, tag = "2")]
    pub begin_time: i64,
    /// 阶段ID
    #[prost(int64, tag = "3")]
    pub phase_id: i64,
    /// fields 4,5 reserved
    ///
    /// 变干时间 (>0 需要浇水)
    #[prost(int64, tag = "6")]
    pub dry_time: i64,
    /// 长草时间 (>0 有杂草)
    #[prost(int64, tag = "7")]
    pub weeds_time: i64,
    /// 生虫时间 (>0 有虫害)
    #[prost(int64, tag = "8")]
    pub insect_time: i64,
    /// 已用肥料
    #[prost(map = "int64, int64", tag = "9")]
    pub ferts_used: ::std::collections::HashMap<i64, i64>,
    /// 变异信息
    #[prost(message, repeated, tag = "10")]
    pub mutants: ::prost::alloc::vec::Vec<MutantInfo>,
}
/// 变异信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MutantInfo {
    #[prost(int64, tag = "1")]
    pub mutant_time: i64,
    #[prost(int64, tag = "2")]
    pub mutant_config_id: i64,
    #[prost(int64, tag = "3")]
    pub weather_id: i64,
}
/// ============ 操作限制 ============
/// 每种操作的每日限制信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OperationLimit {
    /// 操作类型ID
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 今日已操作次数
    #[prost(int64, tag = "2")]
    pub day_times: i64,
    /// 每日操作上限
    #[prost(int64, tag = "3")]
    pub day_times_lt: i64,
    /// 分享ID
    #[prost(int64, tag = "4")]
    pub day_share_id: i64,
    /// 今日已获得经验次数
    #[prost(int64, tag = "5")]
    pub day_exp_times: i64,
    /// 每日可获得经验上限
    #[prost(int64, tag = "6")]
    pub day_ex_times_lt: i64,
    /// 经验分享ID
    #[prost(int64, tag = "7")]
    pub day_exp_share_id: i64,
}
/// --- 获取所有土地 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AllLandsRequest {
    /// 0或自己的GID=查看自己
    #[prost(int64, tag = "1")]
    pub host_gid: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllLandsReply {
    #[prost(message, repeated, tag = "1")]
    pub lands: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 收获 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HarvestRequest {
    /// 要收获的土地ID列表
    #[prost(int64, repeated, tag = "1")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
    /// 农场主GID
    #[prost(int64, tag = "2")]
    pub host_gid: i64,
    /// 是否全部收获
    #[prost(bool, tag = "3")]
    pub is_all: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HarvestReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    /// repeated Item items = 2;     // corepb.Item
    /// repeated Item lost_items = 3;
    #[prost(message, repeated, tag = "4")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 浇水 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WaterLandRequest {
    #[prost(int64, repeated, tag = "1")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, tag = "2")]
    pub host_gid: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WaterLandReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 除草 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WeedOutRequest {
    #[prost(int64, repeated, tag = "1")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, tag = "2")]
    pub host_gid: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WeedOutReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 除虫 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InsecticideRequest {
    #[prost(int64, repeated, tag = "1")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, tag = "2")]
    pub host_gid: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InsecticideReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 播种 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlantItem {
    /// 种子ID
    #[prost(int64, tag = "1")]
    pub seed_id: i64,
    /// 要种植的土地ID列表
    #[prost(int64, repeated, tag = "2")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
    /// 是否自动副产
    #[prost(bool, tag = "3")]
    pub auto_slave: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlantRequest {
    /// land_id -> seed_id (旧版)
    #[prost(map = "int64, int64", tag = "1")]
    pub land_and_seed: ::std::collections::HashMap<i64, i64>,
    /// 新版: 按种子分组种植
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<PlantItem>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlantReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 移除植物 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovePlantRequest {
    #[prost(int64, repeated, tag = "1")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovePlantReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 施肥 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FertilizeRequest {
    #[prost(int64, repeated, tag = "1")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(int64, tag = "2")]
    pub fertilizer_id: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FertilizeReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
    /// 剩余肥料时间
    #[prost(int64, tag = "3")]
    pub fertilizer: i64,
}
/// --- 放虫 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutInsectsRequest {
    #[prost(int64, tag = "1")]
    pub host_gid: i64,
    #[prost(int64, repeated, tag = "2")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutInsectsReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 放草 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutWeedsRequest {
    #[prost(int64, tag = "1")]
    pub host_gid: i64,
    #[prost(int64, repeated, tag = "2")]
    pub land_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutWeedsReply {
    #[prost(message, repeated, tag = "1")]
    pub land: ::prost::alloc::vec::Vec<LandInfo>,
    #[prost(message, repeated, tag = "2")]
    pub operation_limits: ::prost::alloc::vec::Vec<OperationLimit>,
}
/// --- 升级土地 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpgradeLandRequest {
    #[prost(int64, tag = "1")]
    pub land_id: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpgradeLandReply {
    #[prost(message, optional, tag = "1")]
    pub land: ::core::option::Option<LandInfo>,
}
/// --- 解锁土地 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnlockLandRequest {
    #[prost(int64, tag = "1")]
    pub land_id: i64,
    #[prost(bool, tag = "2")]
    pub do_shared: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockLandReply {
    #[prost(message, optional, tag = "1")]
    pub land: ::core::option::Option<LandInfo>,
}
/// --- 检查能否操作 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckCanOperateRequest {
    #[prost(int64, tag = "1")]
    pub host_gid: i64,
    #[prost(int64, tag = "2")]
    pub operation_id: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckCanOperateReply {
    #[prost(bool, tag = "1")]
    pub can_operate: bool,
    #[prost(int64, tag = "2")]
    pub can_steal_num: i64,
}
/// 土地状态变化通知 (被放虫/放草/偷菜等)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LandsNotify {
    /// 变化的土地列表
    #[prost(message, repeated, tag = "1")]
    pub lands: ::prost::alloc::vec::Vec<LandInfo>,
    /// 农场主GID
    #[prost(int64, tag = "2")]
    pub host_gid: i64,
}
/// ============ 生长阶段枚举 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PlantPhase {
    PhaseUnknown = 0,
    /// 种子
    Seed = 1,
    /// 发芽
    Germination = 2,
    /// 小叶
    SmallLeaves = 3,
    /// 大叶
    LargeLeaves = 4,
    /// 开花
    Blooming = 5,
    /// 成熟 (可收获)
    Mature = 6,
    /// 枯死
    Dead = 7,
}
impl PlantPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PhaseUnknown => "PHASE_UNKNOWN",
            Self::Seed => "SEED",
            Self::Germination => "GERMINATION",
            Self::SmallLeaves => "SMALL_LEAVES",
            Self::LargeLeaves => "LARGE_LEAVES",
            Self::Blooming => "BLOOMING",
            Self::Mature => "MATURE",
            Self::Dead => "DEAD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PHASE_UNKNOWN" => Some(Self::PhaseUnknown),
            "SEED" => Some(Self::Seed),
            "GERMINATION" => Some(Self::Germination),
            "SMALL_LEAVES" => Some(Self::SmallLeaves),
            "LARGE_LEAVES" => Some(Self::LargeLeaves),
            "BLOOMING" => Some(Self::Blooming),
            "MATURE" => Some(Self::Mature),
            "DEAD" => Some(Self::Dead),
            _ => None,
        }
    }
}
