// This file is @generated by prost-build.
/// ============ 登录请求 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    /// 字段 1,2 保留未使用
    #[prost(int64, tag = "3")]
    pub sharer_id: i64,
    #[prost(string, tag = "4")]
    pub sharer_open_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub device_info: ::core::option::Option<DeviceInfo>,
    #[prost(int64, tag = "6")]
    pub share_cfg_id: i64,
    #[prost(string, tag = "7")]
    pub scene_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub report_data: ::core::option::Option<ReportData>,
}
/// 设备信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfo {
    /// e.g. "1.6.0.8_20251224"
    #[prost(string, tag = "1")]
    pub client_version: ::prost::alloc::string::String,
    /// e.g. "Windows Unknown x64"
    #[prost(string, tag = "2")]
    pub sys_software: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sys_hardware: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub telecom_oper: ::prost::alloc::string::String,
    /// e.g. "wifi"
    #[prost(string, tag = "5")]
    pub network: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub screen_width: i64,
    #[prost(int64, tag = "7")]
    pub screen_height: i64,
    #[prost(float, tag = "8")]
    pub density: f32,
    /// e.g. "microsoft"
    #[prost(string, tag = "9")]
    pub cpu: ::prost::alloc::string::String,
    #[prost(int64, tag = "10")]
    pub memory: i64,
    #[prost(string, tag = "11")]
    pub gl_render: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub gl_version: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub android_oaid: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub ios_caid: ::prost::alloc::string::String,
}
/// 上报数据
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportData {
    #[prost(string, tag = "1")]
    pub callback: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cd_extend_info: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub click_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub clue_token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub minigame_channel: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub minigame_platid: i32,
    #[prost(string, tag = "7")]
    pub req_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub trackid: ::prost::alloc::string::String,
}
/// ============ 登录回复 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginReply {
    #[prost(message, optional, tag = "1")]
    pub basic: ::core::option::Option<BasicInfo>,
    /// ItemBag item_bag = 2;         // corepb.ItemBag, 复杂结构先跳过
    #[prost(int64, tag = "3")]
    pub time_now_millis: i64,
    #[prost(bool, tag = "4")]
    pub is_first_login: bool,
    /// GuideInfo guide_info = 5;
    #[prost(message, repeated, tag = "6")]
    pub qq_group_infos: ::prost::alloc::vec::Vec<QqGroupInfo>,
    /// Illustrated illustrated = 7;
    /// repeated SystemUnlockItem unlocked_items = 8;
    #[prost(message, optional, tag = "9")]
    pub version_info: ::core::option::Option<VersionInfo>,
    /// MallMsg mall_msg = 10;
    #[prost(int64, tag = "11")]
    pub qq_friend_recommend_authorized: i64,
}
/// 用户基本信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasicInfo {
    #[prost(int64, tag = "1")]
    pub gid: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub level: i64,
    #[prost(int64, tag = "4")]
    pub exp: i64,
    #[prost(int64, tag = "5")]
    pub gold: i64,
    #[prost(string, tag = "6")]
    pub open_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub remark: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int32, tag = "10")]
    pub gender: i32,
    /// repeated AvatarFrame equip_avatar_frames = 11;
    /// map<int64, ShareInfo> share_infos = 12;
    #[prost(int32, tag = "13")]
    pub authorized_status: i32,
    #[prost(bool, tag = "14")]
    pub disable_nudge: bool,
}
/// QQ群信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QqGroupInfo {
    #[prost(string, tag = "1")]
    pub qq_group_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub qq_group_name: ::prost::alloc::string::String,
}
/// 版本信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionInfo {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub version_recommend: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub version_force: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub res_version: ::prost::alloc::string::String,
}
/// ============ 心跳 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatRequest {
    #[prost(int64, tag = "1")]
    pub gid: i64,
    #[prost(string, tag = "2")]
    pub client_version: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeartbeatReply {
    #[prost(int64, tag = "1")]
    pub server_time: i64,
    #[prost(message, optional, tag = "2")]
    pub version_info: ::core::option::Option<VersionInfo>,
}
/// ============ 上报分享点击 ============
/// 用于已登录状态下处理分享链接（触发好友申请）
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportArkClickRequest {
    #[prost(int64, tag = "1")]
    pub sharer_id: i64,
    #[prost(string, tag = "2")]
    pub sharer_open_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub share_cfg_id: i64,
    #[prost(string, tag = "4")]
    pub scene_id: ::prost::alloc::string::String,
}
/// 通常为空响应
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ReportArkClickReply {}
/// 基本信息变化通知 (升级/金币变化等)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasicNotify {
    #[prost(message, optional, tag = "1")]
    pub basic: ::core::option::Option<BasicInfo>,
}
