// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetTodayClaimStatusRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RedPacketInfo {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bool, tag = "3")]
    pub can_claim: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTodayClaimStatusReply {
    #[prost(message, repeated, tag = "1")]
    pub infos: ::prost::alloc::vec::Vec<RedPacketInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimRedPacketRequest {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimRedPacketReply {
    #[prost(int32, tag = "1")]
    pub status: i32,
    #[prost(message, optional, tag = "2")]
    pub item: ::core::option::Option<super::super::corepb::Item>,
}
