// This file is @generated by prost-build.
/// ============ 单个任务 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Task {
    /// 任务ID
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 当前进度
    #[prost(int64, tag = "2")]
    pub progress: i64,
    /// 是否已领取
    #[prost(bool, tag = "3")]
    pub is_claimed: bool,
    /// 是否已解锁
    #[prost(bool, tag = "4")]
    pub is_unlocked: bool,
    /// 奖励列表
    #[prost(message, repeated, tag = "5")]
    pub rewards: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    /// 总进度
    #[prost(int64, tag = "6")]
    pub total_progress: i64,
    /// 分享倍数 (>1 表示可分享翻倍)
    #[prost(int64, tag = "7")]
    pub share_multiple: i64,
    /// 参数
    #[prost(string, repeated, tag = "8")]
    pub params: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 描述
    #[prost(string, tag = "9")]
    pub desc: ::prost::alloc::string::String,
    /// 任务类型
    #[prost(int32, tag = "10")]
    pub task_type: i32,
    /// 分组
    #[prost(int64, tag = "11")]
    pub group: i64,
    /// 条件类型
    #[prost(int64, tag = "12")]
    pub cond_type: i64,
    /// 是否显示文本
    #[prost(int64, tag = "13")]
    pub is_show_text: i64,
}
/// ============ 活跃度奖励项 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveReward {
    /// 奖励档位ID
    #[prost(int64, tag = "1")]
    pub point_id: i64,
    /// 所需进度
    #[prost(int64, tag = "2")]
    pub need_progress: i64,
    /// ActiveStatus
    #[prost(int32, tag = "3")]
    pub status: i32,
    /// 奖励物品
    #[prost(message, repeated, tag = "4")]
    pub rewards: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
/// ============ 活跃度 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Active {
    /// ActiveType
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// 当前活跃度
    #[prost(int64, tag = "2")]
    pub progress: i64,
    /// 各档位奖励
    #[prost(message, repeated, tag = "3")]
    pub rewards: ::prost::alloc::vec::Vec<ActiveReward>,
}
/// ============ 任务信息汇总 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskInfo {
    /// 成长任务列表
    #[prost(message, repeated, tag = "1")]
    pub growth_tasks: ::prost::alloc::vec::Vec<Task>,
    /// 每日任务列表
    #[prost(message, repeated, tag = "2")]
    pub daily_tasks: ::prost::alloc::vec::Vec<Task>,
    /// 其他任务
    #[prost(message, repeated, tag = "3")]
    pub tasks: ::prost::alloc::vec::Vec<Task>,
    /// 活跃度奖励
    #[prost(message, repeated, tag = "4")]
    pub actives: ::prost::alloc::vec::Vec<Active>,
}
/// --- 获取任务信息 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TaskInfoRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskInfoReply {
    #[prost(message, optional, tag = "1")]
    pub task_info: ::core::option::Option<TaskInfo>,
}
/// --- 领取单个任务奖励 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimTaskRewardRequest {
    /// 任务ID
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 是否使用分享翻倍 (true=翻倍, false=普通领取)
    #[prost(bool, tag = "2")]
    pub do_shared: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimTaskRewardReply {
    /// 获得的物品
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    /// 更新后的任务信息
    #[prost(message, optional, tag = "2")]
    pub task_info: ::core::option::Option<TaskInfo>,
    /// 补偿物品
    #[prost(message, repeated, tag = "3")]
    pub compensated_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
/// --- 批量领取任务奖励 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchClaimTaskRewardRequest {
    /// 任务ID列表
    #[prost(int64, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<i64>,
    /// 是否使用分享翻倍
    #[prost(bool, tag = "2")]
    pub do_shared: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchClaimTaskRewardReply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    #[prost(message, optional, tag = "2")]
    pub task_info: ::core::option::Option<TaskInfo>,
    #[prost(message, repeated, tag = "3")]
    pub compensated_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
/// --- 领取活跃度奖励 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimDailyRewardRequest {
    /// ActiveType
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// 要领取的奖励档位ID列表
    #[prost(int64, repeated, tag = "2")]
    pub point_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimDailyRewardReply {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
    #[prost(message, optional, tag = "2")]
    pub task_info: ::core::option::Option<TaskInfo>,
    #[prost(message, repeated, tag = "3")]
    pub compensated_items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
/// --- 客户端上报进度 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClientReportProgressRequest {
    #[prost(int64, tag = "1")]
    pub task_id: i64,
    #[prost(int64, tag = "2")]
    pub progress: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientReportProgressReply {
    #[prost(message, optional, tag = "1")]
    pub task_info: ::core::option::Option<TaskInfo>,
}
/// 任务状态变化通知
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskInfoNotify {
    #[prost(message, optional, tag = "1")]
    pub task_info: ::core::option::Option<TaskInfo>,
}
/// ============ 活跃度奖励 ============
/// ============ 活跃度类型 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActiveType {
    Unknown = 0,
    /// 日活跃
    Dailyactive = 1,
    /// 周活跃
    Weeklyactive = 2,
}
impl ActiveType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ACTIVE_TYPE_UNKNOWN",
            Self::Dailyactive => "DAILYACTIVE",
            Self::Weeklyactive => "WEEKLYACTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVE_TYPE_UNKNOWN" => Some(Self::Unknown),
            "DAILYACTIVE" => Some(Self::Dailyactive),
            "WEEKLYACTIVE" => Some(Self::Weeklyactive),
            _ => None,
        }
    }
}
/// ============ 活跃度状态 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActiveStatus {
    NoneUnknown = 0,
    /// 未达标
    Wait = 1,
    /// 已达标可领取
    Done = 2,
}
impl ActiveStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NoneUnknown => "NONE_UNKNOWN",
            Self::Wait => "WAIT",
            Self::Done => "DONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE_UNKNOWN" => Some(Self::NoneUnknown),
            "WAIT" => Some(Self::Wait),
            "DONE" => Some(Self::Done),
            _ => None,
        }
    }
}
