// This file is @generated by prost-build.
/// ============ 进入好友农场 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EnterRequest {
    /// 好友的GID
    #[prost(int64, tag = "1")]
    pub host_gid: i64,
    /// EnterReason 进入原因
    #[prost(int32, tag = "2")]
    pub reason: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnterReply {
    /// 好友基本信息
    #[prost(message, optional, tag = "1")]
    pub basic: ::core::option::Option<super::userpb::BasicInfo>,
    /// 好友的所有土地
    #[prost(message, repeated, tag = "2")]
    pub lands: ::prost::alloc::vec::Vec<super::plantpb::LandInfo>,
}
/// ============ 离开好友农场 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveRequest {
    /// 好友的GID
    #[prost(int64, tag = "1")]
    pub host_gid: i64,
}
/// 空消息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveReply {}
/// ============ 进入原因枚举 ============
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EnterReason {
    Unknown = 0,
    Bubble = 1,
    Friend = 2,
    Interact = 3,
}
impl EnterReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ENTER_REASON_UNKNOWN",
            Self::Bubble => "ENTER_REASON_BUBBLE",
            Self::Friend => "ENTER_REASON_FRIEND",
            Self::Interact => "ENTER_REASON_INTERACT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENTER_REASON_UNKNOWN" => Some(Self::Unknown),
            "ENTER_REASON_BUBBLE" => Some(Self::Bubble),
            "ENTER_REASON_FRIEND" => Some(Self::Friend),
            "ENTER_REASON_INTERACT" => Some(Self::Interact),
            _ => None,
        }
    }
}
