// This file is @generated by prost-build.
/// --- 获取每日礼包状态 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetDailyGiftStatusRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetDailyGiftStatusReply {
    /// 是否可以领取
    #[prost(bool, tag = "1")]
    pub can_claim: bool,
    /// 是否有礼包
    #[prost(bool, tag = "2")]
    pub has_gift: bool,
}
/// --- 领取每日礼包 ---
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClaimDailyGiftRequest {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimDailyGiftReply {
    /// 奖励物品列表
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<super::super::corepb::Item>,
}
