// This file is @generated by prost-build.
/// 消息元信息
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Meta {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub method_name: ::prost::alloc::string::String,
    /// MessageType enum
    #[prost(int32, tag = "3")]
    pub message_type: i32,
    #[prost(int64, tag = "4")]
    pub client_seq: i64,
    #[prost(int64, tag = "5")]
    pub server_seq: i64,
    #[prost(int64, tag = "6")]
    pub error_code: i64,
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(map = "string, bytes", tag = "8")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::vec::Vec<u8>,
    >,
}
/// 每个WS帧的结构
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(message, optional, tag = "1")]
    pub meta: ::core::option::Option<Meta>,
    #[prost(bytes = "vec", tag = "2")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
/// 服务器推送事件
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventMessage {
    #[prost(string, tag = "1")]
    pub message_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
/// 被踢下线通知
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickoutNotify {
    #[prost(int64, tag = "1")]
    pub reason: i64,
    #[prost(string, tag = "2")]
    pub reason_message: ::prost::alloc::string::String,
}
/// Meta.Type 枚举
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    None = 0,
    Request = 1,
    Response = 2,
    Notify = 3,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "None",
            Self::Request => "Request",
            Self::Response => "Response",
            Self::Notify => "Notify",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "None" => Some(Self::None),
            "Request" => Some(Self::Request),
            "Response" => Some(Self::Response),
            "Notify" => Some(Self::Notify),
            _ => None,
        }
    }
}
